#!/usr/bin/env python

import subprocess
import sys


def main():
    npx_cmd = [
        "npx",
        "--no-install",
        "elm-review",
        "--ignore-dirs=tests",
    ]
    res = subprocess.run(
        ["git", "ls-files", "-z", "-o", "--exclude-standard"],
        check=True,
        capture_output=True,
    )

    if untracked := res.stdout[:-1]:
        npx_cmd.extend(
            [
                "--ignore-files",
                b",".join(untracked.split(b"\0")),
            ],
        )

    res = subprocess.run(npx_cmd)
    print(res)
    sys.exit(res.returncode)


if __name__ == "__main__":
    main()
