#!/usr/bin/env python

import subprocess
import sys


def main():
    res = subprocess.run(
        ["git", "ls-files", "-z", "-o", "--exclude-standard"],
        check=True,
        capture_output=True,
    )
    untracked = res.stdout[:-1].split(b"\0")

    ignore = b",".join(untracked)

    res = subprocess.run(
        [
            "npx",
            "--no-install",
            "elm-review",
            "--ignore-dirs=tests",
            "--ignore-files",
            ignore,
        ],
    )
    print(res)
    sys.exit(res.returncode)


if __name__ == "__main__":
    main()
